import { createContext, useContext, useEffect, useState } from 'react'
import { z } from 'zod/v4'
import { C1Component, ThemeProvider } from '@thesysai/genui-sdk'
import '@crayonai/react-ui/styles/index.css'
import { api, fmtTs, sourceOf } from './api'
import { Button, ImpactCell, Skeleton, SourceBadge, StatusPill } from './primitives'

// The four custom components C1 composes the workspace from. Each prefers
// the LIVE case (App polls every 2s) over its generated props, so the
// workspace stays reactive — a draft attaching or a status morph shows up
// without re-calling C1.

const WorkspaceCtx = createContext(null)
export const useWorkspace = () => useContext(WorkspaceCtx)

export function ImpactBrief(props) {
  // Live case data wins outright when present — C1's job is composition;
  // props only carry data when there is no live case to read from.
  const { liveCase } = useWorkspace()
  const c = liveCase || {}
  const live = !!liveCase
  const impact = live ? c.impact_level : props.impactLevel
  const summary = live ? c.summary : props.summary
  const effective = live ? c.effective_date : props.effectiveDate
  const url = live ? c.url : props.url
  if (live && !c.impact_level) {
    if (c.status === 'CLOSED') {
      // auto-closed as not relevant — no brief exists; show the agent's reasoning
      const closeNote = (c.timeline || []).filter((e) => e.action === 'closed').pop()?.note
      return (
        <div className="border-b border-hairline px-4 py-3">
          <div className="mb-2 flex items-center gap-2">
            <SourceBadge source={sourceOf(c)} />
            <span className="rounded bg-stone-100 px-1.5 py-0.5 text-[11px] font-semibold text-stone-600">
              NOT RELEVANT
            </span>
          </div>
          <p className="text-[13px] leading-relaxed text-ink-2">
            {closeNote || 'Classified not relevant to our charter — closed with no action.'}
          </p>
          {c.url && (
            <a
              href={c.url}
              target="_blank"
              rel="noreferrer"
              className="mt-1.5 inline-block text-[12px] font-medium text-blue-600 hover:underline"
            >
              View source document
            </a>
          )}
        </div>
      )
    }
    return (
      <div className="border-b border-hairline px-4 py-3">
        <div className="mb-2 flex items-center gap-2">
          <SourceBadge source={sourceOf(c)} />
          <span className="text-[11px] text-ink-3">classifying impact…</span>
        </div>
        <div className="space-y-2">
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-4/5" />
        </div>
      </div>
    )
  }
  return (
    <div className="border-b border-hairline px-4 py-3">
      <div className="mb-2 flex items-center gap-2">
        <SourceBadge source={sourceOf(c) || props.source} />
        <ImpactCell level={impact} />
        {effective && (
          <span className="tnum text-[11px] text-ink-3">effective {effective}</span>
        )}
      </div>
      <p className="text-[13px] leading-relaxed text-ink-2">{summary}</p>
      {url && (
        <a
          href={url}
          target="_blank"
          rel="noreferrer"
          className="mt-1.5 inline-block text-[12px] font-medium text-blue-600 hover:underline"
        >
          View source document
        </a>
      )}
    </div>
  )
}

export function DraftMemo(props) {
  const { liveCase } = useWorkspace()
  const draft = liveCase?.draft ?? props
  const pending = draft.pending
  if (pending && liveCase?.status === 'CLOSED') {
    return (
      <div className="border-b border-hairline px-4 py-3 text-[12px] text-ink-3">
        No notification — case closed with no action required.
      </div>
    )
  }
  return (
    <div className="border-b border-hairline px-4 py-3">
      <div className="mb-2 flex items-center gap-2">
        <span className="rounded bg-stone-100 px-1.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-ink-2">
          Draft — generated by Canary
        </span>
        {pending && <span className="text-[11px] text-ink-3">drafting…</span>}
      </div>
      {pending ? (
        <div className="space-y-2">
          <Skeleton className="h-3 w-2/3" />
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-full" />
          <Skeleton className="h-3 w-4/5" />
        </div>
      ) : (
        <div className="rounded-md border border-hairline bg-rail px-3 py-2.5">
          <div className="border-b border-hairline pb-2 text-[12px]">
            <div>
              <span className="text-ink-3">To: </span>
              <span className="font-medium">{(draft.to || []).join(', ')}</span>
            </div>
            <div>
              <span className="text-ink-3">Subject: </span>
              <span className="font-medium">{draft.subject}</span>
            </div>
          </div>
          <p className="whitespace-pre-line pt-2 text-[13px] leading-relaxed text-ink-2">
            {draft.body}
          </p>
        </div>
      )}
    </div>
  )
}

export function RecommendedActions(props) {
  // C1-generated analysis — the one component whose content the model
  // derives rather than copies; intentionally NOT live-overridden.
  const items = props.items || []
  if (!items.length) return null
  return (
    <div className="border-b border-hairline px-4 py-3">
      <div className="mb-2 flex items-center gap-2">
        <span className="text-[10px] font-semibold tracking-wide text-ink-3 uppercase">
          Close-out checklist
        </span>
        <span className="rounded bg-stone-100 px-1.5 py-0.5 text-[10px] text-ink-3">
          generated by C1
        </span>
      </div>
      <div className="space-y-2">
        {items.map((it, i) => {
          const owner = it.owner ?? it.unit
          const deadline = it.deadline ?? it.timeframe
          return (
            <div key={i} className="flex items-start gap-2 text-[12.5px]">
              <span className="mt-0.5 h-3.5 w-3.5 shrink-0 rounded-sm border border-hairline" />
              <span className="min-w-0 flex-1">
                <span className="text-ink">{it.action}</span>
                <span className="mt-0.5 flex items-center gap-1.5">
                  {owner && (
                    <span className="rounded bg-stone-100 px-1.5 py-0.5 text-[11px] whitespace-nowrap text-ink-2">
                      {owner}
                    </span>
                  )}
                  {deadline && <span className="tnum text-[11px] text-ink-3">{deadline}</span>}
                </span>
              </span>
            </div>
          )
        })}
      </div>
    </div>
  )
}

// lifecycle tracker — the pizza-tracker strip at the top of every workspace
const STAGES = ['Detected', 'Triaged', 'Notified', 'In progress', 'Closed']
const STAGE_OF = { NEW: 0, TRIAGED: 1, NOTIFIED: 2, IN_PROGRESS: 3, CLOSED: 4 }

export function LifecycleTracker({ status, impact }) {
  const cur = STAGE_OF[status] ?? 0
  const held = status === 'TRIAGED' && impact === 'HIGH'
  const doneColor = status === 'CLOSED' ? 'bg-green-600' : 'bg-blue-600'
  return (
    <div className="border-b border-hairline px-4 pt-3 pb-2">
      <div className="flex items-center">
        {STAGES.map((s, i) => (
          <span key={s} className="contents">
            {i > 0 && (
              <span className={`mx-1 h-px flex-1 ${i <= cur ? doneColor : 'bg-hairline'}`} />
            )}
            <span
              className={`h-2.5 w-2.5 shrink-0 rounded-full transition-colors duration-200 ${
                i < cur || (i === cur && status === 'CLOSED')
                  ? doneColor
                  : i === cur
                    ? `border-2 bg-white ${held ? 'border-red-700' : 'border-blue-600'}`
                    : 'border border-hairline bg-white'
              }`}
            />
          </span>
        ))}
      </div>
      <div className="mt-1 flex justify-between">
        {STAGES.map((s, i) => (
          <span
            key={s}
            className={`text-[9px] tracking-wide uppercase ${
              i === cur && status !== 'CLOSED'
                ? held
                  ? 'font-semibold text-red-700'
                  : 'font-semibold text-blue-700'
                : i <= cur
                  ? 'text-ink-2'
                  : 'text-ink-3'
            }`}
          >
            {i === 1 && held ? 'Awaiting review' : s}
          </span>
        ))}
      </div>
    </div>
  )
}

function Modal({ title, onClose, children }) {
  return (
    <div
      id="canary-modal"
      className="fixed inset-0 z-50 flex items-center justify-center bg-stone-900/25"
      onClick={onClose}
    >
      <div
        className="w-[440px] rounded-lg border border-hairline bg-white p-4 shadow-lg"
        onClick={(e) => e.stopPropagation()}
        onKeyDown={(e) => e.key === 'Escape' && onClose()}
      >
        <div className="mb-3 text-[14px] font-semibold">{title}</div>
        {children}
      </div>
    </div>
  )
}

const ACTION_LABEL = {
  detected: 'Detected',
  triaged: 'Triaged',
  draft_pending: 'Drafting notification',
  drafted: 'Notification drafted',
  published: 'Notification delivered',
  escalated: 'Escalated for review',
  notified: 'Owners notified',
  in_progress: 'Update',
  update: 'Update',
  closed: 'Case closed',
}

export function CaseTimeline(props) {
  const { liveCase } = useWorkspace()
  const entries = liveCase?.timeline ?? props.entries ?? []
  return (
    <div className="flex-1 overflow-y-auto px-4 py-3">
      <div className="mb-2 text-[10px] font-semibold uppercase tracking-wide text-ink-3">
        Timeline
      </div>
      <div className="space-y-0">
        {entries.map((e, i) => (
          <div key={i} className="relative flex gap-3 pb-4 last:pb-0">
            {i < entries.length - 1 && (
              <span className="absolute top-4 left-[5px] h-full w-px bg-hairline" />
            )}
            <span
              className={`relative mt-1 h-[11px] w-[11px] shrink-0 rounded-full ${
                e.actor === 'agent' ? 'border-2 border-blue-600 bg-white' : 'bg-ink'
              }`}
            />
            <div className="min-w-0">
              <div className="flex items-baseline gap-2">
                <span
                  className={`text-[11px] font-semibold ${
                    e.actor === 'agent' ? 'text-blue-600' : 'text-ink'
                  }`}
                >
                  {e.actor === 'agent' ? 'Agent' : 'Saad E.'}
                </span>
                <span className="text-[12px] font-medium text-ink">
                  {ACTION_LABEL[e.action] || e.action}
                </span>
                <span className="tnum text-[11px] text-ink-3">{fmtTs(e.ts)}</span>
              </div>
              {e.note && e.action !== 'drafted' && (
                <p className="mt-0.5 text-[12px] leading-snug text-ink-2">{e.note}</p>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}

export function CaseActions(props) {
  const { liveCase, actions } = useWorkspace()
  const status = liveCase?.status ?? props.status
  const impact = liveCase?.impact_level ?? props.impactLevel
  const [modal, setModal] = useState(null) // null | 'note' | 'close'
  const [note, setNote] = useState('')
  const canApprove = status === 'TRIAGED' && impact === 'HIGH'
  const closed = status === 'CLOSED'
  const dismiss = () => {
    setModal(null)
    setNote('')
  }
  const submitNote = () => {
    if (note.trim()) actions.update(note.trim())
    dismiss()
  }
  const confirmClose = () => {
    actions.close(note.trim())
    dismiss()
  }
  if (closed) {
    return (
      <div className="border-t border-hairline bg-white px-4 py-3 text-[12px] text-ink-3">
        Case closed · read-only
      </div>
    )
  }
  return (
    <div className="border-t border-hairline bg-white px-4 py-3">
      <div className="flex items-center gap-2">
        {canApprove && (
          <Button variant="primary" onClick={() => actions.approve()}>
            Approve &amp; Notify
          </Button>
        )}
        <Button onClick={() => setModal('note')}>Add Update</Button>
        <Button onClick={() => setModal('close')}>Close Case</Button>
      </div>

      {modal === 'note' && (
        <Modal title="Add case update" onClose={dismiss}>
          <textarea
            autoFocus
            rows={5}
            value={note}
            onChange={(e) => setNote(e.target.value)}
            onKeyDown={(e) => (e.metaKey || e.ctrlKey) && e.key === 'Enter' && submitNote()}
            placeholder="What happened? Vendor calls, system changes, evidence filed… (⌘↵ to save)"
            className="w-full resize-y rounded-md border border-hairline px-2.5 py-2 text-[13px] leading-relaxed outline-none focus:ring-2 focus:ring-blue-600"
          />
          <div className="mt-3 flex justify-end gap-2">
            <Button onClick={dismiss}>Cancel</Button>
            <Button variant="primary" onClick={submitNote} disabled={!note.trim()}>
              Save update
            </Button>
          </div>
        </Modal>
      )}

      {modal === 'close' && (
        <Modal title="Close this case?" onClose={dismiss}>
          <p className="text-[13px] leading-relaxed text-ink-2">
            Closing marks the case resolved and makes it read-only. The full timeline stays in
            the audit record.
          </p>
          <textarea
            autoFocus
            rows={3}
            value={note}
            onChange={(e) => setNote(e.target.value)}
            placeholder="Closing note (optional) — e.g. what was verified before closing"
            className="mt-3 w-full resize-y rounded-md border border-hairline px-2.5 py-2 text-[13px] leading-relaxed outline-none focus:ring-2 focus:ring-blue-600"
          />
          <div className="mt-3 flex justify-end gap-2">
            <Button onClick={dismiss}>Cancel</Button>
            <Button variant="primary" onClick={confirmClose}>
              Close case
            </Button>
          </div>
        </Modal>
      )}
    </div>
  )
}

// Schemas must mirror harness/server.py C1_COMPONENT_SCHEMAS — same keys in
// the same order; the v2 renderer maps the spec's positional args via them.
// The SDK requires Zod (v4 API) schemas client-side.
const timelineEntry = z.object({
  ts: z.string(),
  actor: z.enum(['agent', 'human']),
  action: z.string(),
  note: z.string().optional(),
})

const CUSTOM_COMPONENTS = {
  ImpactBrief: {
    component: ImpactBrief,
    schema: z.object({
      title: z.string(),
      source: z.string(),
      impactLevel: z.enum(['LOW', 'MED', 'HIGH']),
      effectiveDate: z.string().nullable().optional(),
      summary: z.string(),
      url: z.string().nullable().optional(),
    }),
  },
  DraftMemo: {
    component: DraftMemo,
    schema: z.object({
      pending: z.boolean(),
      to: z.array(z.string()).optional(),
      subject: z.string().optional(),
      body: z.string().optional(),
    }),
  },
  CaseTimeline: {
    component: CaseTimeline,
    schema: z.object({ entries: z.array(timelineEntry) }),
  },
  RecommendedActions: {
    component: RecommendedActions,
    schema: z.object({
      items: z.array(
        z.object({
          action: z.string(),
          owner: z.string().optional(),
          deadline: z.string().optional(),
        }),
      ),
    }),
  },
  CaseActions: {
    component: CaseActions,
    schema: z.object({
      caseId: z.number(),
      status: z.string(),
      impactLevel: z.string(),
    }),
  },
}

function LocalWorkspace({ c }) {
  // Tripwire fallback: same components, fixed composition, no C1 call.
  return (
    <>
      <ImpactBrief />
      <DraftMemo {...(c.draft || {})} />
      <CaseTimeline entries={c.timeline} />
      <CaseActions caseId={c.id} status={c.status} impactLevel={c.impact_level} />
    </>
  )
}

// A case is "stable" once its draft exists (or it's past TRIAGED) — specs
// generated then include real RecommendedActions, so they're safe to cache.
const isStable = (c) =>
  c &&
  (['NOTIFIED', 'IN_PROGRESS', 'CLOSED'].includes(c.status) ||
    (c.timeline || []).some((e) => e.action === 'drafted'))

const specCache = new Map() // case id → resolved {c1,...} or in-flight Promise

export function prefetchWorkspace(c) {
  if (!isStable(c) || specCache.has(c.id)) return
  const p = api
    .c1case(c.id)
    .then((r) => {
      if (r.c1) specCache.set(c.id, r)
      else specCache.delete(c.id)
      return r
    })
    .catch(() => specCache.delete(c.id))
  specCache.set(c.id, p) // in-flight marker dedupes concurrent prefetches
}

export function Workspace({ liveCase, actions, onClose, expanded, onToggleExpand }) {
  const [spec, setSpec] = useState(null) // {c1} | {fallback} | null while loading
  const id = liveCase?.id
  const stable = isStable(liveCase)

  useEffect(() => {
    let staleFlag = false
    if (id == null) return
    const cached = specCache.get(id)
    if (cached && !(cached instanceof Promise)) {
      setSpec(cached)
      return
    }
    setSpec(null)
    const p = cached instanceof Promise ? cached : api.c1case(id)
    p.then((r) => {
      if (staleFlag || !r) return
      setSpec(r)
      if (r.c1 && stable) specCache.set(id, r)
    }).catch((e) => !staleFlag && setSpec({ error: String(e) }))
    return () => {
      staleFlag = true
    }
    // re-runs when stability flips: an early-clicked case upgrades to the
    // full workspace (with RecommendedActions) once its draft lands
  }, [id, stable])

  if (!liveCase) return null
  const ctx = { liveCase, actions }
  return (
    <WorkspaceCtx.Provider value={ctx}>
      <div className="panel-in flex h-full min-h-0 flex-col overflow-hidden bg-white">
        <div className="flex items-start gap-2 border-b border-hairline px-4 py-3">
          <div className="min-w-0 flex-1">
            <div className="line-clamp-2 text-[15px] leading-snug font-semibold">{liveCase.title}</div>
            <div className="mt-1">
              <StatusPill
                status={liveCase.status}
                impact={liveCase.impact_level}
                escalated
              />
            </div>
          </div>
          <button
            onClick={onToggleExpand}
            className="cursor-pointer rounded p-1 text-ink-3 hover:bg-stone-100 hover:text-ink"
            title={expanded ? 'Restore panel' : 'Expand to full width'}
          >
            {expanded ? '⤡' : '⤢'}
          </button>
          <button
            onClick={onClose}
            className="cursor-pointer rounded p-1 text-ink-3 hover:bg-stone-100 hover:text-ink"
            title="Close (Esc)"
          >
            ✕
          </button>
        </div>

        <LifecycleTracker status={liveCase.status} impact={liveCase.impact_level} />

        {spec === null && (
          // progressive: live DB facts paint immediately in the local
          // composition while C1 composes; the generated workspace swaps in
          <div className="flex min-h-0 flex-1 flex-col overflow-y-auto">
            <LocalWorkspace c={liveCase} />
          </div>
        )}

        {spec?.c1 && (
          <div className="min-h-0 flex-1 overflow-y-auto">
            <ThemeProvider mode="light">
              <C1Component c1Response={spec.c1} customComponents={CUSTOM_COMPONENTS} />
            </ThemeProvider>
          </div>
        )}

        {spec && !spec.c1 && (
          <div className="flex min-h-0 flex-1 flex-col overflow-y-auto">
            <LocalWorkspace c={liveCase} />
          </div>
        )}

        <div className="border-t border-hairline px-4 py-1.5 text-[10px] text-ink-3">
          {spec?.c1
            ? 'workspace generated by Thesys C1'
            : spec
              ? 'local workspace (C1 unavailable)'
              : 'Thesys C1 composing workspace… (live data shown)'}
        </div>
      </div>
    </WorkspaceCtx.Provider>
  )
}
